# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 715)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/logo/logo_optimass.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 0, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:black-gray ; \n"
"background-color:white ; \n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_2.setObjectName("label_2")
        self.bt_thu_nho = QtWidgets.QPushButton(self.centralwidget)
        self.bt_thu_nho.setGeometry(QtCore.QRect(1010, 0, 31, 31))
        self.bt_thu_nho.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/mimiiii_flaticon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_thu_nho.setIcon(icon)
        self.bt_thu_nho.setObjectName("bt_thu_nho")
        self.bt_thu_phong = QtWidgets.QPushButton(self.centralwidget)
        self.bt_thu_phong.setGeometry(QtCore.QRect(1040, 0, 31, 31))
        self.bt_thu_phong.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/minimize_flaticon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_thu_phong.setIcon(icon1)
        self.bt_thu_phong.setObjectName("bt_thu_phong")
        self.bt_thoat = QtWidgets.QPushButton(self.centralwidget)
        self.bt_thoat.setGeometry(QtCore.QRect(1070, 0, 31, 31))
        self.bt_thoat.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/close_screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_thoat.setIcon(icon2)
        self.bt_thoat.setObjectName("bt_thoat")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 80, 1091, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setStyleSheet("")
        self.page_main.setObjectName("page_main")
        self.tab_main = QtWidgets.QTabWidget(self.page_main)
        self.tab_main.setGeometry(QtCore.QRect(0, 0, 1081, 571))
        self.tab_main.setStyleSheet("")
        self.tab_main.setIconSize(QtCore.QSize(60, 60))
        self.tab_main.setObjectName("tab_main")
        self.tab_gioi_thieu = QtWidgets.QWidget()
        self.tab_gioi_thieu.setObjectName("tab_gioi_thieu")
        self.tab_main.addTab(self.tab_gioi_thieu, "")
        self.tab_tinh_nang = QtWidgets.QWidget()
        self.tab_tinh_nang.setStyleSheet("background-color: gray  ;")
        self.tab_tinh_nang.setObjectName("tab_tinh_nang")
        self.bt_dan_duong = QtWidgets.QPushButton(self.tab_tinh_nang)
        self.bt_dan_duong.setGeometry(QtCore.QRect(90, 190, 221, 211))
        self.bt_dan_duong.setStyleSheet("QPushButton#bt_dan_duong{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_dan_duong:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/destination.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_dan_duong.setIcon(icon3)
        self.bt_dan_duong.setIconSize(QtCore.QSize(50, 50))
        self.bt_dan_duong.setObjectName("bt_dan_duong")
        self.label_3 = QtWidgets.QLabel(self.tab_tinh_nang)
        self.label_3.setGeometry(QtCore.QRect(280, 50, 441, 71))
        self.label_3.setStyleSheet("color : Blue ; \n"
"background-color: white;\n"
"border: 2px solid black;\n"
"font : 30px ; \n"
"border-radius : 20px ;\n"
"text-align: center;  /* Căn giữa văn bản theo chiều ngang */\n"
" qproperty-alignment: \'AlignCenter\';\n"
"vertical-align: middle;  /* Căn giữa văn bản theo chiều dọc */")
        self.label_3.setObjectName("label_3")
        self.bt_diem_danh = QtWidgets.QPushButton(self.tab_tinh_nang)
        self.bt_diem_danh.setGeometry(QtCore.QRect(380, 190, 221, 211))
        self.bt_diem_danh.setStyleSheet("QPushButton#bt_diem_danh{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_diem_danh:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/Icon/list_flation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_diem_danh.setIcon(icon4)
        self.bt_diem_danh.setIconSize(QtCore.QSize(50, 50))
        self.bt_diem_danh.setObjectName("bt_diem_danh")
        self.bt_tra_cuu = QtWidgets.QPushButton(self.tab_tinh_nang)
        self.bt_tra_cuu.setGeometry(QtCore.QRect(670, 190, 221, 211))
        self.bt_tra_cuu.setStyleSheet("QPushButton#bt_tra_cuu{\n"
"       border-radius :20px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid red;\n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_tra_cuu:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/Icon/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_tra_cuu.setIcon(icon5)
        self.bt_tra_cuu.setIconSize(QtCore.QSize(50, 50))
        self.bt_tra_cuu.setObjectName("bt_tra_cuu")
        self.tab_main.addTab(self.tab_tinh_nang, "")
        self.tab_cai_dat = QtWidgets.QWidget()
        self.tab_cai_dat.setStyleSheet("background-color: gray  ;")
        self.tab_cai_dat.setObjectName("tab_cai_dat")
        self.label_5 = QtWidgets.QLabel(self.tab_cai_dat)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 281, 61))
        self.label_5.setStyleSheet("color : Blue ; \n"
"background-color: white;\n"
"border: 2px solid black;\n"
"font : 30px ; \n"
"border-radius : 20px ;\n"
"text-align: center;  /* Căn giữa văn bản theo chiều ngang */\n"
" qproperty-alignment: \'AlignCenter\';\n"
"vertical-align: middle;  /* Căn giữa văn bản theo chiều dọc */")
        self.label_5.setObjectName("label_5")
        self.bt_check_cam = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_check_cam.setGeometry(QtCore.QRect(180, 160, 191, 61))
        self.bt_check_cam.setStyleSheet("QPushButton#bt_check_cam{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_check_cam:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_check_cam.setIcon(icon6)
        self.bt_check_cam.setIconSize(QtCore.QSize(26, 26))
        self.bt_check_cam.setAutoRepeatInterval(100)
        self.bt_check_cam.setDefault(False)
        self.bt_check_cam.setObjectName("bt_check_cam")
        self.bt_setup_cam = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_setup_cam.setGeometry(QtCore.QRect(180, 250, 191, 61))
        self.bt_setup_cam.setStyleSheet("QPushButton#bt_setup_cam{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_setup_cam:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/xoafont_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_setup_cam.setIcon(icon7)
        self.bt_setup_cam.setIconSize(QtCore.QSize(26, 26))
        self.bt_setup_cam.setObjectName("bt_setup_cam")
        self.bt_wifi = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_wifi.setGeometry(QtCore.QRect(180, 340, 191, 61))
        self.bt_wifi.setStyleSheet("QPushButton#bt_wifi{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_wifi:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/wifi_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_wifi.setIcon(icon8)
        self.bt_wifi.setIconSize(QtCore.QSize(26, 26))
        self.bt_wifi.setObjectName("bt_wifi")
        self.bt_them = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_them.setGeometry(QtCore.QRect(180, 420, 191, 61))
        self.bt_them.setStyleSheet("QPushButton#bt_them{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_them:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_them.setIcon(icon9)
        self.bt_them.setIconSize(QtCore.QSize(26, 26))
        self.bt_them.setObjectName("bt_them")
        self.bt_dinh_vi = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_dinh_vi.setGeometry(QtCore.QRect(520, 160, 181, 61))
        self.bt_dinh_vi.setStyleSheet("QPushButton#bt_dinh_vi{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_dinh_vi:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_dinh_vi.setObjectName("bt_dinh_vi")
        self.bt_set_home = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_set_home.setGeometry(QtCore.QRect(520, 250, 181, 61))
        self.bt_set_home.setStyleSheet("QPushButton#bt_set_home{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_set_home:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_set_home.setObjectName("bt_set_home")
        self.bt_di_chuyen = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_di_chuyen.setGeometry(QtCore.QRect(520, 340, 181, 61))
        self.bt_di_chuyen.setStyleSheet("QPushButton#bt_di_chuyen{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_di_chuyen:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_di_chuyen.setObjectName("bt_di_chuyen")
        self.bt_setup = QtWidgets.QPushButton(self.tab_cai_dat)
        self.bt_setup.setGeometry(QtCore.QRect(520, 420, 181, 61))
        self.bt_setup.setStyleSheet("QPushButton#bt_setup{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_setup:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_setup.setObjectName("bt_setup")
        self.tab_main.addTab(self.tab_cai_dat, "")
        self.stackedWidget.addWidget(self.page_main)
        self.page_diem_danh = QtWidgets.QWidget()
        self.page_diem_danh.setObjectName("page_diem_danh")
        self.label_4 = QtWidgets.QLabel(self.page_diem_danh)
        self.label_4.setGeometry(QtCore.QRect(370, 50, 311, 51))
        self.label_4.setStyleSheet("color : Blue ; \n"
"background-color: white;\n"
"border: 2px solid black;\n"
"font : 30px ; \n"
"border-radius : 20px ;\n"
"text-align: center;  /* Căn giữa văn bản theo chiều ngang */\n"
" qproperty-alignment: \'AlignCenter\';\n"
"vertical-align: middle;  /* Căn giữa văn bản theo chiều dọc */")
        self.label_4.setObjectName("label_4")
        self.bt_check_in = QtWidgets.QPushButton(self.page_diem_danh)
        self.bt_check_in.setGeometry(QtCore.QRect(230, 210, 201, 191))
        self.bt_check_in.setStyleSheet("QPushButton#bt_check_in\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_check_in:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_check_in.setObjectName("bt_check_in")
        self.bt_check_out = QtWidgets.QPushButton(self.page_diem_danh)
        self.bt_check_out.setGeometry(QtCore.QRect(600, 210, 201, 191))
        self.bt_check_out.setStyleSheet("QPushButton#bt_check_out\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_check_out:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_check_out.setObjectName("bt_check_out")
        self.bt_back_diem_danh = QtWidgets.QPushButton(self.page_diem_danh)
        self.bt_back_diem_danh.setGeometry(QtCore.QRect(934, 50, 151, 41))
        self.bt_back_diem_danh.setStyleSheet("QPushButton#bt_back_diem_danh\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_back_diem_danh:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/muiten_cong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_back_diem_danh.setIcon(icon10)
        self.bt_back_diem_danh.setIconSize(QtCore.QSize(30, 30))
        self.bt_back_diem_danh.setObjectName("bt_back_diem_danh")
        self.stackedWidget.addWidget(self.page_diem_danh)
        self.page_setup = QtWidgets.QWidget()
        self.page_setup.setObjectName("page_setup")
        self.label_6 = QtWidgets.QLabel(self.page_setup)
        self.label_6.setGeometry(QtCore.QRect(390, 50, 231, 41))
        self.label_6.setStyleSheet("color : Blue ; \n"
"background-color: white;\n"
"border: 2px solid black;\n"
"font : 30px ; \n"
"border-radius : 20px ;\n"
"text-align: center;  /* Căn giữa văn bản theo chiều ngang */\n"
" qproperty-alignment: \'AlignCenter\';\n"
"vertical-align: middle;  /* Căn giữa văn bản theo chiều dọc */")
        self.label_6.setObjectName("label_6")
        self.bt_setup_robot = QtWidgets.QPushButton(self.page_setup)
        self.bt_setup_robot.setGeometry(QtCore.QRect(130, 180, 181, 171))
        self.bt_setup_robot.setStyleSheet("QPushButton#bt_setup_robot\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_setup_robot:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_setup_robot.setObjectName("bt_setup_robot")
        self.bt_setup_dinh_vi = QtWidgets.QPushButton(self.page_setup)
        self.bt_setup_dinh_vi.setGeometry(QtCore.QRect(410, 180, 181, 171))
        self.bt_setup_dinh_vi.setStyleSheet("QPushButton#bt_setup_dinh_vi\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_setup_dinh_vi:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_setup_dinh_vi.setObjectName("bt_setup_dinh_vi")
        self.bt_setup_tk = QtWidgets.QPushButton(self.page_setup)
        self.bt_setup_tk.setGeometry(QtCore.QRect(690, 180, 181, 171))
        self.bt_setup_tk.setStyleSheet("QPushButton#bt_setup_tk{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_setup_tk:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_setup_tk.setObjectName("bt_setup_tk")
        self.bt_back_setup = QtWidgets.QPushButton(self.page_setup)
        self.bt_back_setup.setGeometry(QtCore.QRect(910, 50, 171, 41))
        self.bt_back_setup.setStyleSheet("QPushButton#bt_back_setup\n"
"{\n"
"       border-radius :20px;\n"
"border: 2px solid red;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(220, 220, 220);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_back_setup:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(50, 192, 240);\n"
"}\n"
"")
        self.bt_back_setup.setIcon(icon10)
        self.bt_back_setup.setIconSize(QtCore.QSize(30, 30))
        self.bt_back_setup.setObjectName("bt_back_setup")
        self.stackedWidget.addWidget(self.page_setup)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ten Robot"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_gioi_thieu), _translate("MainWindow", "Giới Thiệu "))
        self.bt_dan_duong.setText(_translate("MainWindow", "Dẫn Đường"))
        self.label_3.setText(_translate("MainWindow", "CHỌN TÍNH NĂNG "))
        self.bt_diem_danh.setText(_translate("MainWindow", "Điểm Danh"))
        self.bt_tra_cuu.setText(_translate("MainWindow", "Tra Cứu"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_tinh_nang), _translate("MainWindow", "Tính Năng"))
        self.label_5.setText(_translate("MainWindow", "Thông số "))
        self.bt_check_cam.setText(_translate("MainWindow", "Check Cam"))
        self.bt_setup_cam.setText(_translate("MainWindow", "Setup Cam"))
        self.bt_wifi.setText(_translate("MainWindow", "Wifi"))
        self.bt_them.setText(_translate("MainWindow", "Thêm"))
        self.bt_dinh_vi.setText(_translate("MainWindow", "Định Vị"))
        self.bt_set_home.setText(_translate("MainWindow", "Set Home"))
        self.bt_di_chuyen.setText(_translate("MainWindow", "Di Chuyển"))
        self.bt_setup.setText(_translate("MainWindow", "Setup"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_cai_dat), _translate("MainWindow", "Cài Đặt"))
        self.label_4.setText(_translate("MainWindow", "Điểm Danh "))
        self.bt_check_in.setText(_translate("MainWindow", "Check In"))
        self.bt_check_out.setText(_translate("MainWindow", "Check Out"))
        self.bt_back_diem_danh.setText(_translate("MainWindow", "Quay Lại"))
        self.label_6.setText(_translate("MainWindow", "Setup"))
        self.bt_setup_robot.setText(_translate("MainWindow", "Setup Robot"))
        self.bt_setup_dinh_vi.setText(_translate("MainWindow", "Setup Định Vị"))
        self.bt_setup_tk.setText(_translate("MainWindow", "Setup Tài Khoản"))
        self.bt_back_setup.setText(_translate("MainWindow", "Quay Lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
